title: Hiếu nè
description: Blog của Hiếu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hieuphan2708.tk/" # the base hostname & protocol for your site, e.g. http://example.com

title-separator: "-"

author:
  name: Blog của Hiếu
  github: hieuphan2708
  facebook: hieu.baby
  email: pnhieu.stu14@medvnu.edu.vn


# Build settings
timezone: "Asia/Ho_Chi_Minh"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:categories/:title
# paginate: 24
# paginate_path: "/chuyende/page-:num"

# Facebook App ID
# fb_app_id: "208703010516551"

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

plugins:
  - jekyll-feed
  - jekyll-sitemap
