- title: "Trans"
  url: "https://github.com/dinhanhthi/TaniaJekyll"
  description: "Tài liệu tham khảo chất lượng được dịch sang Tiếng Việt"
  img: "tania-jekyll.svg"
- title: "Tech"
  url: "https://github.com/dinhanhthi/NoteTheme"
  description: "Ứng dụng công nghệ thông tin vào quá trình học tập ngành y"
  img: "notetheme.svg"
- title: "Help"
  url: "https://github.com/dinhanhthi/nxfem"
  description: "Tải giùm bạn sách ngoại văn, các bài báo khoa học, tài liệu Uptodate, BMJ, Dynamed. Ai cần gì thì mình lấy, mình không public vì vấn đề bản quyền"
  img: "nxfem.png"
- title: "Auto"
  url: "http://math2it.com/gioi-thieu"
  description: "Bot tải tài liệu UpToDate"
  img: "math2it.gif"

