- title: "Trans"
  url: "https://hieuphan2708.github.io/chuyende"
  description: "Tài liệu tham khảo chất lượng được dịch sang Tiếng Việt"
  img: "tania-jekyll.svg"
- title: "Tech"
  url: "https://hieuphan2708.github.io/congcu"
  description: "Ứng dụng công nghệ thông tin vào quá trình học tập ngành y"
  img: "notetheme.svg"
- title: "Get"
  url: "http://m.me/hieu.baby"
  description: "Tải giúp bạn sách ngoại văn, các bài báo khoa học, tài liệu Uptodate, BMJ, Dynamed"
  img: "nxfem.svg"
- title: "Bot"
  url: "http://m.me/pnhieu.stu14"
  description: "Bot Messenger tải tài liệu UpToDate."
  img: "bot.svg"

