- title: "Trans"
  url: "https://github.com/dinhanhthi/TaniaJekyll"
  description: "Tài liệu tham khảo chất lượng được dịch sang Tiếng Việt"
  img: "tania-jekyll.svg"
- title: "Tech"
  url: "https://github.com/dinhanhthi/NoteTheme"
  description: "Ứng dụng công nghệ thông tin vào quá trình học tập ngành y"
  img: "notetheme.svg"
- title: "NXFEM"
  url: "https://github.com/dinhanhthi/nxfem"
  description: "Tải giúp bạn sách ngoại văn, các bài báo khoa học, tài liệu Uptodate, BMJ, Dynamed"
  img: "nxfem.png"
- title: "Bot"
  url: "http://math2it.com/gioi-thieu"
  description: "A Vietnamese site for intuitive knowledge (Maths, LaTeX, Education and Technology)."
  img: "math2it.gif"

